#ifndef ROLLING_CYLINDER_STRINGS_H_
#define ROLLING_CYLINDER_STRINGS_H_

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "LifNeuron/position_inputs_0.h"
#include "LifNeuron/position_inputs_1.h"
#include "LifNeuron/position_inputs_2.h"
#include "LifNeuron/position_inputs_3.h"
#include "LifNeuron/position_inputs_4.h"
#include "LifNeuron/position_inputs_5.h"
#include "LifNeuron/position_inputs_6.h"
#include "LifNeuron/position_inputs_7.h"
#include "LifNeuron/position_inputs_8.h"
#include "LifNeuron/position_inputs_9.h"
#include "LifNeuron/position_inputs_10.h"
#include "LifNeuron/position_inputs_11.h"
#include "LifNeuron/position_inputs_12.h"
#include "LifNeuron/position_inputs_13.h"
#include "LifNeuron/position_inputs_14.h"
#include "LifNeuron/position_inputs_15.h"
#include "LifNeuron/position_inputs_16.h"
#include "LifNeuron/position_inputs_17.h"
#include "LifNeuron/position_inputs_18.h"
#include "LifNeuron/position_inputs_19.h"
#include "LifNeuron/position_inputs_20.h"
#include "LifNeuron/position_inputs_21.h"
#include "LifNeuron/position_inputs_22.h"
#include "LifNeuron/position_inputs_23.h"
#include "LifNeuron/position_inputs_24.h"
#include "LifNeuron/position_inputs_25.h"
#include "LifNeuron/position_inputs_26.h"
#include "LifNeuron/position_inputs_27.h"
#include "LifNeuron/position_inputs_28.h"
#include "LifNeuron/position_inputs_29.h"
#include "LifNeuron/position_inputs_30.h"
#include "LifNeuron/position_inputs_31.h"
#include "LifNeuron/position_inputs_32.h"
#include "LifNeuron/position_inputs_33.h"
#include "LifNeuron/position_inputs_34.h"
#include "LifNeuron/position_inputs_35.h"
#include "LifNeuron/position_inputs_36.h"
#include "LifNeuron/position_inputs_37.h"
#include "LifNeuron/position_inputs_38.h"
#include "LifNeuron/position_inputs_39.h"
#include "LifNeuron/position_inputs_40.h"
#include "LifNeuron/position_inputs_41.h"
#include "LifNeuron/position_inputs_42.h"
#include "LifNeuron/position_inputs_43.h"
#include "LifNeuron/position_inputs_44.h"
#include "LifNeuron/position_inputs_45.h"
#include "LifNeuron/position_inputs_46.h"
#include "LifNeuron/position_inputs_47.h"
#include "LifNeuron/position_inputs_48.h"
#include "LifNeuron/position_inputs_49.h"
#include "LifNeuron/position_inputs_50.h"
#include "LifNeuron/position_inputs_51.h"
#include "LifNeuron/position_inputs_52.h"
#include "LifNeuron/position_inputs_53.h"
#include "LifNeuron/position_inputs_54.h"
#include "LifNeuron/position_inputs_55.h"
#include "LifNeuron/position_inputs_56.h"
#include "LifNeuron/position_inputs_57.h"
#include "LifNeuron/position_inputs_58.h"
#include "LifNeuron/position_inputs_59.h"
#include "LifNeuron/position_inputs_60.h"
#include "LifNeuron/position_inputs_61.h"
#include "LifNeuron/position_inputs_62.h"
#include "LifNeuron/position_inputs_63.h"
#include "LifNeuron/position_inputs_64.h"
#include "LifNeuron/position_inputs_65.h"
#include "LifNeuron/position_inputs_66.h"
#include "LifNeuron/position_inputs_67.h"
#include "LifNeuron/position_inputs_68.h"
#include "LifNeuron/position_inputs_69.h"
#include "LifNeuron/position_inputs_70.h"
#include "LifNeuron/position_inputs_71.h"
#include "LifNeuron/position_inputs_72.h"
#include "LifNeuron/position_inputs_73.h"
#include "LifNeuron/position_inputs_74.h"
#include "LifNeuron/position_inputs_75.h"
#include "LifNeuron/position_inputs_76.h"
#include "LifNeuron/position_inputs_77.h"
#include "LifNeuron/position_inputs_78.h"
#include "LifNeuron/position_inputs_79.h"
#include "LifNeuron/position_inputs_80.h"
#include "LifNeuron/position_inputs_81.h"
#include "LifNeuron/position_inputs_82.h"
#include "LifNeuron/position_inputs_83.h"
#include "LifNeuron/position_inputs_84.h"
#include "LifNeuron/position_inputs_85.h"
#include "LifNeuron/position_inputs_86.h"
#include "LifNeuron/position_inputs_87.h"
#include "LifNeuron/position_inputs_88.h"
#include "LifNeuron/position_inputs_89.h"
#include "LifNeuron/position_inputs_90.h"
#include "LifNeuron/position_inputs_91.h"
#include "LifNeuron/position_inputs_92.h"
#include "LifNeuron/position_inputs_93.h"
#include "LifNeuron/position_inputs_94.h"
#include "LifNeuron/position_inputs_95.h"
#include "LifNeuron/position_inputs_96.h"
#include "LifNeuron/position_inputs_97.h"
#include "LifNeuron/position_inputs_98.h"
#include "LifNeuron/position_inputs_99.h"
#include "LifNeuron/position_inputs_100.h"
#include "LifNeuron/position_inputs_101.h"
#include "LifNeuron/position_inputs_102.h"
#include "LifNeuron/position_inputs_103.h"
#include "LifNeuron/position_inputs_104.h"
#include "LifNeuron/position_inputs_105.h"
#include "LifNeuron/position_inputs_106.h"
#include "LifNeuron/position_inputs_107.h"
#include "LifNeuron/position_inputs_108.h"
#include "LifNeuron/position_inputs_109.h"
#include "LifNeuron/position_inputs_110.h"
#include "LifNeuron/position_inputs_111.h"
#include "LifNeuron/position_inputs_112.h"
#include "LifNeuron/position_inputs_113.h"
#include "LifNeuron/position_inputs_114.h"
#include "LifNeuron/position_inputs_115.h"
#include "LifNeuron/position_inputs_116.h"
#include "LifNeuron/position_inputs_117.h"
#include "LifNeuron/position_inputs_118.h"
#include "LifNeuron/position_inputs_119.h"
#include "LifNeuron/position_inputs_120.h"
#include "LifNeuron/position_inputs_121.h"
#include "LifNeuron/position_inputs_122.h"
#include "LifNeuron/position_inputs_123.h"
#include "LifNeuron/position_inputs_124.h"
#include "LifNeuron/position_inputs_125.h"
#include "LifNeuron/position_inputs_126.h"
#include "LifNeuron/position_inputs_127.h"
#include "LifNeuron/position_inputs_128.h"
#include "LifNeuron/position_inputs_129.h"
#include "LifNeuron/position_inputs_130.h"
#include "LifNeuron/position_inputs_131.h"
#include "LifNeuron/position_inputs_132.h"
#include "LifNeuron/position_inputs_133.h"
#include "LifNeuron/position_inputs_134.h"
#include "LifNeuron/position_inputs_135.h"
#include "LifNeuron/position_inputs_136.h"
#include "LifNeuron/position_inputs_137.h"
#include "LifNeuron/position_inputs_138.h"
#include "LifNeuron/position_inputs_139.h"
#include "LifNeuron/position_inputs_140.h"
#include "LifNeuron/position_inputs_141.h"
#include "LifNeuron/position_inputs_142.h"
#include "LifNeuron/position_inputs_143.h"
#include "LifNeuron/position_inputs_144.h"
#include "LifNeuron/position_inputs_145.h"
#include "LifNeuron/position_inputs_146.h"
#include "LifNeuron/position_inputs_147.h"
#include "LifNeuron/position_inputs_148.h"
#include "LifNeuron/position_inputs_149.h"
#include "LifNeuron/position_inputs_150.h"
#include "LifNeuron/position_inputs_151.h"
#include "LifNeuron/position_inputs_152.h"
#include "LifNeuron/position_inputs_153.h"
#include "LifNeuron/position_inputs_154.h"
#include "LifNeuron/position_inputs_155.h"
#include "LifNeuron/position_inputs_156.h"
#include "LifNeuron/position_inputs_157.h"
#include "LifNeuron/position_inputs_158.h"
#include "LifNeuron/position_inputs_159.h"
#include "LifNeuron/position_inputs_160.h"
#include "LifNeuron/position_inputs_161.h"
#include "LifNeuron/position_inputs_162.h"
#include "LifNeuron/position_inputs_163.h"
#include "LifNeuron/position_inputs_164.h"
#include "LifNeuron/position_inputs_165.h"
#include "LifNeuron/position_inputs_166.h"
#include "LifNeuron/position_inputs_167.h"
#include "LifNeuron/position_inputs_168.h"
#include "LifNeuron/position_inputs_169.h"
#include "LifNeuron/position_inputs_170.h"
#include "LifNeuron/position_inputs_171.h"
#include "LifNeuron/position_inputs_172.h"
#include "LifNeuron/position_inputs_173.h"
#include "LifNeuron/position_inputs_174.h"
#include "LifNeuron/position_inputs_175.h"
#include "LifNeuron/position_inputs_176.h"
#include "LifNeuron/position_inputs_177.h"
#include "LifNeuron/position_inputs_178.h"
#include "LifNeuron/position_inputs_179.h"
#include "LifNeuron/position_inputs_180.h"
#include "LifNeuron/position_inputs_181.h"
#include "LifNeuron/position_inputs_182.h"
#include "LifNeuron/position_inputs_183.h"
#include "LifNeuron/position_inputs_184.h"
#include "LifNeuron/position_inputs_185.h"
#include "LifNeuron/position_inputs_186.h"
#include "LifNeuron/position_inputs_187.h"
#include "LifNeuron/position_inputs_188.h"
#include "LifNeuron/position_inputs_189.h"
#include "LifNeuron/position_inputs_190.h"
#include "LifNeuron/position_inputs_191.h"
#include "LifNeuron/position_inputs_192.h"
#include "LifNeuron/position_inputs_193.h"
#include "LifNeuron/position_inputs_194.h"
#include "LifNeuron/position_inputs_195.h"
#include "LifNeuron/position_inputs_196.h"
#include "LifNeuron/position_inputs_197.h"
#include "LifNeuron/position_inputs_198.h"
#include "LifNeuron/position_inputs_199.h"
#include "LowPass/position_conn_synapse0.h"
#include "LowPass/position_conn_synapse1.h"
#include "LowPass/position_conn_synapse2.h"
#include "LowPass/position_conn_synapse3.h"
#include "LowPass/position_conn_synapse4.h"
#include "LowPass/position_conn_synapse5.h"
#include "LowPass/position_conn_synapse6.h"
#include "LowPass/position_conn_synapse7.h"
#include "LowPass/position_conn_synapse8.h"
#include "LowPass/position_conn_synapse9.h"
#include "LowPass/position_conn_synapse10.h"
#include "LowPass/position_conn_synapse11.h"
#include "LowPass/position_conn_synapse12.h"
#include "LowPass/position_conn_synapse13.h"
#include "LowPass/position_conn_synapse14.h"
#include "LowPass/position_conn_synapse15.h"
#include "LowPass/position_conn_synapse16.h"
#include "LowPass/position_conn_synapse17.h"
#include "LowPass/position_conn_synapse18.h"
#include "LowPass/position_conn_synapse19.h"
#include "LowPass/position_conn_synapse20.h"
#include "LowPass/position_conn_synapse21.h"
#include "LowPass/position_conn_synapse22.h"
#include "LowPass/position_conn_synapse23.h"
#include "LowPass/position_conn_synapse24.h"
#include "LowPass/position_conn_synapse25.h"
#include "LowPass/position_conn_synapse26.h"
#include "LowPass/position_conn_synapse27.h"
#include "LowPass/position_conn_synapse28.h"
#include "LowPass/position_conn_synapse29.h"
#include "LowPass/position_conn_synapse30.h"
#include "LowPass/position_conn_synapse31.h"
#include "LowPass/position_conn_synapse32.h"
#include "LowPass/position_conn_synapse33.h"
#include "LowPass/position_conn_synapse34.h"
#include "LowPass/position_conn_synapse35.h"
#include "LowPass/position_conn_synapse36.h"
#include "LowPass/position_conn_synapse37.h"
#include "LowPass/position_conn_synapse38.h"
#include "LowPass/position_conn_synapse39.h"
#include "LowPass/position_conn_synapse40.h"
#include "LowPass/position_conn_synapse41.h"
#include "LowPass/position_conn_synapse42.h"
#include "LowPass/position_conn_synapse43.h"
#include "LowPass/position_conn_synapse44.h"
#include "LowPass/position_conn_synapse45.h"
#include "LowPass/position_conn_synapse46.h"
#include "LowPass/position_conn_synapse47.h"
#include "LowPass/position_conn_synapse48.h"
#include "LowPass/position_conn_synapse49.h"
#include "LowPass/position_conn_synapse50.h"
#include "LowPass/position_conn_synapse51.h"
#include "LowPass/position_conn_synapse52.h"
#include "LowPass/position_conn_synapse53.h"
#include "LowPass/position_conn_synapse54.h"
#include "LowPass/position_conn_synapse55.h"
#include "LowPass/position_conn_synapse56.h"
#include "LowPass/position_conn_synapse57.h"
#include "LowPass/position_conn_synapse58.h"
#include "LowPass/position_conn_synapse59.h"
#include "LowPass/position_conn_synapse60.h"
#include "LowPass/position_conn_synapse61.h"
#include "LowPass/position_conn_synapse62.h"
#include "LowPass/position_conn_synapse63.h"
#include "LowPass/position_conn_synapse64.h"
#include "LowPass/position_conn_synapse65.h"
#include "LowPass/position_conn_synapse66.h"
#include "LowPass/position_conn_synapse67.h"
#include "LowPass/position_conn_synapse68.h"
#include "LowPass/position_conn_synapse69.h"
#include "LowPass/position_conn_synapse70.h"
#include "LowPass/position_conn_synapse71.h"
#include "LowPass/position_conn_synapse72.h"
#include "LowPass/position_conn_synapse73.h"
#include "LowPass/position_conn_synapse74.h"
#include "LowPass/position_conn_synapse75.h"
#include "LowPass/position_conn_synapse76.h"
#include "LowPass/position_conn_synapse77.h"
#include "LowPass/position_conn_synapse78.h"
#include "LowPass/position_conn_synapse79.h"
#include "LowPass/position_conn_synapse80.h"
#include "LowPass/position_conn_synapse81.h"
#include "LowPass/position_conn_synapse82.h"
#include "LowPass/position_conn_synapse83.h"
#include "LowPass/position_conn_synapse84.h"
#include "LowPass/position_conn_synapse85.h"
#include "LowPass/position_conn_synapse86.h"
#include "LowPass/position_conn_synapse87.h"
#include "LowPass/position_conn_synapse88.h"
#include "LowPass/position_conn_synapse89.h"
#include "LowPass/position_conn_synapse90.h"
#include "LowPass/position_conn_synapse91.h"
#include "LowPass/position_conn_synapse92.h"
#include "LowPass/position_conn_synapse93.h"
#include "LowPass/position_conn_synapse94.h"
#include "LowPass/position_conn_synapse95.h"
#include "LowPass/position_conn_synapse96.h"
#include "LowPass/position_conn_synapse97.h"
#include "LowPass/position_conn_synapse98.h"
#include "LowPass/position_conn_synapse99.h"
#include "LowPass/position_conn_synapse100.h"
#include "LowPass/position_conn_synapse101.h"
#include "LowPass/position_conn_synapse102.h"
#include "LowPass/position_conn_synapse103.h"
#include "LowPass/position_conn_synapse104.h"
#include "LowPass/position_conn_synapse105.h"
#include "LowPass/position_conn_synapse106.h"
#include "LowPass/position_conn_synapse107.h"
#include "LowPass/position_conn_synapse108.h"
#include "LowPass/position_conn_synapse109.h"
#include "LowPass/position_conn_synapse110.h"
#include "LowPass/position_conn_synapse111.h"
#include "LowPass/position_conn_synapse112.h"
#include "LowPass/position_conn_synapse113.h"
#include "LowPass/position_conn_synapse114.h"
#include "LowPass/position_conn_synapse115.h"
#include "LowPass/position_conn_synapse116.h"
#include "LowPass/position_conn_synapse117.h"
#include "LowPass/position_conn_synapse118.h"
#include "LowPass/position_conn_synapse119.h"
#include "LowPass/position_conn_synapse120.h"
#include "LowPass/position_conn_synapse121.h"
#include "LowPass/position_conn_synapse122.h"
#include "LowPass/position_conn_synapse123.h"
#include "LowPass/position_conn_synapse124.h"
#include "LowPass/position_conn_synapse125.h"
#include "LowPass/position_conn_synapse126.h"
#include "LowPass/position_conn_synapse127.h"
#include "LowPass/position_conn_synapse128.h"
#include "LowPass/position_conn_synapse129.h"
#include "LowPass/position_conn_synapse130.h"
#include "LowPass/position_conn_synapse131.h"
#include "LowPass/position_conn_synapse132.h"
#include "LowPass/position_conn_synapse133.h"
#include "LowPass/position_conn_synapse134.h"
#include "LowPass/position_conn_synapse135.h"
#include "LowPass/position_conn_synapse136.h"
#include "LowPass/position_conn_synapse137.h"
#include "LowPass/position_conn_synapse138.h"
#include "LowPass/position_conn_synapse139.h"
#include "LowPass/position_conn_synapse140.h"
#include "LowPass/position_conn_synapse141.h"
#include "LowPass/position_conn_synapse142.h"
#include "LowPass/position_conn_synapse143.h"
#include "LowPass/position_conn_synapse144.h"
#include "LowPass/position_conn_synapse145.h"
#include "LowPass/position_conn_synapse146.h"
#include "LowPass/position_conn_synapse147.h"
#include "LowPass/position_conn_synapse148.h"
#include "LowPass/position_conn_synapse149.h"
#include "LowPass/position_conn_synapse150.h"
#include "LowPass/position_conn_synapse151.h"
#include "LowPass/position_conn_synapse152.h"
#include "LowPass/position_conn_synapse153.h"
#include "LowPass/position_conn_synapse154.h"
#include "LowPass/position_conn_synapse155.h"
#include "LowPass/position_conn_synapse156.h"
#include "LowPass/position_conn_synapse157.h"
#include "LowPass/position_conn_synapse158.h"
#include "LowPass/position_conn_synapse159.h"
#include "LowPass/position_conn_synapse160.h"
#include "LowPass/position_conn_synapse161.h"
#include "LowPass/position_conn_synapse162.h"
#include "LowPass/position_conn_synapse163.h"
#include "LowPass/position_conn_synapse164.h"
#include "LowPass/position_conn_synapse165.h"
#include "LowPass/position_conn_synapse166.h"
#include "LowPass/position_conn_synapse167.h"
#include "LowPass/position_conn_synapse168.h"
#include "LowPass/position_conn_synapse169.h"
#include "LowPass/position_conn_synapse170.h"
#include "LowPass/position_conn_synapse171.h"
#include "LowPass/position_conn_synapse172.h"
#include "LowPass/position_conn_synapse173.h"
#include "LowPass/position_conn_synapse174.h"
#include "LowPass/position_conn_synapse175.h"
#include "LowPass/position_conn_synapse176.h"
#include "LowPass/position_conn_synapse177.h"
#include "LowPass/position_conn_synapse178.h"
#include "LowPass/position_conn_synapse179.h"
#include "LowPass/position_conn_synapse180.h"
#include "LowPass/position_conn_synapse181.h"
#include "LowPass/position_conn_synapse182.h"
#include "LowPass/position_conn_synapse183.h"
#include "LowPass/position_conn_synapse184.h"
#include "LowPass/position_conn_synapse185.h"
#include "LowPass/position_conn_synapse186.h"
#include "LowPass/position_conn_synapse187.h"
#include "LowPass/position_conn_synapse188.h"
#include "LowPass/position_conn_synapse189.h"
#include "LowPass/position_conn_synapse190.h"
#include "LowPass/position_conn_synapse191.h"
#include "LowPass/position_conn_synapse192.h"
#include "LowPass/position_conn_synapse193.h"
#include "LowPass/position_conn_synapse194.h"
#include "LowPass/position_conn_synapse195.h"
#include "LowPass/position_conn_synapse196.h"
#include "LowPass/position_conn_synapse197.h"
#include "LowPass/position_conn_synapse198.h"
#include "LowPass/position_conn_synapse199.h"

#include <stdbool.h>

#include "config.h"

// rolling_cylinder_strings Data Struct
typedef struct {
    
    // Declare Inputs
    double strings_0_in;
    double strings_1_in;
    double strings_2_in;
    double setpoint_0_in;
    double setpoint_1_in;
    
    // Declare Outputs
    double strings_0_out;
    double strings_1_out;
    double strings_2_out;

    // Declare Daughter Automata
    PositionInputs0 position_inputs_0_data;
    PositionInputs1 position_inputs_1_data;
    PositionInputs2 position_inputs_2_data;
    PositionInputs3 position_inputs_3_data;
    PositionInputs4 position_inputs_4_data;
    PositionInputs5 position_inputs_5_data;
    PositionInputs6 position_inputs_6_data;
    PositionInputs7 position_inputs_7_data;
    PositionInputs8 position_inputs_8_data;
    PositionInputs9 position_inputs_9_data;
    PositionInputs10 position_inputs_10_data;
    PositionInputs11 position_inputs_11_data;
    PositionInputs12 position_inputs_12_data;
    PositionInputs13 position_inputs_13_data;
    PositionInputs14 position_inputs_14_data;
    PositionInputs15 position_inputs_15_data;
    PositionInputs16 position_inputs_16_data;
    PositionInputs17 position_inputs_17_data;
    PositionInputs18 position_inputs_18_data;
    PositionInputs19 position_inputs_19_data;
    PositionInputs20 position_inputs_20_data;
    PositionInputs21 position_inputs_21_data;
    PositionInputs22 position_inputs_22_data;
    PositionInputs23 position_inputs_23_data;
    PositionInputs24 position_inputs_24_data;
    PositionInputs25 position_inputs_25_data;
    PositionInputs26 position_inputs_26_data;
    PositionInputs27 position_inputs_27_data;
    PositionInputs28 position_inputs_28_data;
    PositionInputs29 position_inputs_29_data;
    PositionInputs30 position_inputs_30_data;
    PositionInputs31 position_inputs_31_data;
    PositionInputs32 position_inputs_32_data;
    PositionInputs33 position_inputs_33_data;
    PositionInputs34 position_inputs_34_data;
    PositionInputs35 position_inputs_35_data;
    PositionInputs36 position_inputs_36_data;
    PositionInputs37 position_inputs_37_data;
    PositionInputs38 position_inputs_38_data;
    PositionInputs39 position_inputs_39_data;
    PositionInputs40 position_inputs_40_data;
    PositionInputs41 position_inputs_41_data;
    PositionInputs42 position_inputs_42_data;
    PositionInputs43 position_inputs_43_data;
    PositionInputs44 position_inputs_44_data;
    PositionInputs45 position_inputs_45_data;
    PositionInputs46 position_inputs_46_data;
    PositionInputs47 position_inputs_47_data;
    PositionInputs48 position_inputs_48_data;
    PositionInputs49 position_inputs_49_data;
    PositionInputs50 position_inputs_50_data;
    PositionInputs51 position_inputs_51_data;
    PositionInputs52 position_inputs_52_data;
    PositionInputs53 position_inputs_53_data;
    PositionInputs54 position_inputs_54_data;
    PositionInputs55 position_inputs_55_data;
    PositionInputs56 position_inputs_56_data;
    PositionInputs57 position_inputs_57_data;
    PositionInputs58 position_inputs_58_data;
    PositionInputs59 position_inputs_59_data;
    PositionInputs60 position_inputs_60_data;
    PositionInputs61 position_inputs_61_data;
    PositionInputs62 position_inputs_62_data;
    PositionInputs63 position_inputs_63_data;
    PositionInputs64 position_inputs_64_data;
    PositionInputs65 position_inputs_65_data;
    PositionInputs66 position_inputs_66_data;
    PositionInputs67 position_inputs_67_data;
    PositionInputs68 position_inputs_68_data;
    PositionInputs69 position_inputs_69_data;
    PositionInputs70 position_inputs_70_data;
    PositionInputs71 position_inputs_71_data;
    PositionInputs72 position_inputs_72_data;
    PositionInputs73 position_inputs_73_data;
    PositionInputs74 position_inputs_74_data;
    PositionInputs75 position_inputs_75_data;
    PositionInputs76 position_inputs_76_data;
    PositionInputs77 position_inputs_77_data;
    PositionInputs78 position_inputs_78_data;
    PositionInputs79 position_inputs_79_data;
    PositionInputs80 position_inputs_80_data;
    PositionInputs81 position_inputs_81_data;
    PositionInputs82 position_inputs_82_data;
    PositionInputs83 position_inputs_83_data;
    PositionInputs84 position_inputs_84_data;
    PositionInputs85 position_inputs_85_data;
    PositionInputs86 position_inputs_86_data;
    PositionInputs87 position_inputs_87_data;
    PositionInputs88 position_inputs_88_data;
    PositionInputs89 position_inputs_89_data;
    PositionInputs90 position_inputs_90_data;
    PositionInputs91 position_inputs_91_data;
    PositionInputs92 position_inputs_92_data;
    PositionInputs93 position_inputs_93_data;
    PositionInputs94 position_inputs_94_data;
    PositionInputs95 position_inputs_95_data;
    PositionInputs96 position_inputs_96_data;
    PositionInputs97 position_inputs_97_data;
    PositionInputs98 position_inputs_98_data;
    PositionInputs99 position_inputs_99_data;
    PositionInputs100 position_inputs_100_data;
    PositionInputs101 position_inputs_101_data;
    PositionInputs102 position_inputs_102_data;
    PositionInputs103 position_inputs_103_data;
    PositionInputs104 position_inputs_104_data;
    PositionInputs105 position_inputs_105_data;
    PositionInputs106 position_inputs_106_data;
    PositionInputs107 position_inputs_107_data;
    PositionInputs108 position_inputs_108_data;
    PositionInputs109 position_inputs_109_data;
    PositionInputs110 position_inputs_110_data;
    PositionInputs111 position_inputs_111_data;
    PositionInputs112 position_inputs_112_data;
    PositionInputs113 position_inputs_113_data;
    PositionInputs114 position_inputs_114_data;
    PositionInputs115 position_inputs_115_data;
    PositionInputs116 position_inputs_116_data;
    PositionInputs117 position_inputs_117_data;
    PositionInputs118 position_inputs_118_data;
    PositionInputs119 position_inputs_119_data;
    PositionInputs120 position_inputs_120_data;
    PositionInputs121 position_inputs_121_data;
    PositionInputs122 position_inputs_122_data;
    PositionInputs123 position_inputs_123_data;
    PositionInputs124 position_inputs_124_data;
    PositionInputs125 position_inputs_125_data;
    PositionInputs126 position_inputs_126_data;
    PositionInputs127 position_inputs_127_data;
    PositionInputs128 position_inputs_128_data;
    PositionInputs129 position_inputs_129_data;
    PositionInputs130 position_inputs_130_data;
    PositionInputs131 position_inputs_131_data;
    PositionInputs132 position_inputs_132_data;
    PositionInputs133 position_inputs_133_data;
    PositionInputs134 position_inputs_134_data;
    PositionInputs135 position_inputs_135_data;
    PositionInputs136 position_inputs_136_data;
    PositionInputs137 position_inputs_137_data;
    PositionInputs138 position_inputs_138_data;
    PositionInputs139 position_inputs_139_data;
    PositionInputs140 position_inputs_140_data;
    PositionInputs141 position_inputs_141_data;
    PositionInputs142 position_inputs_142_data;
    PositionInputs143 position_inputs_143_data;
    PositionInputs144 position_inputs_144_data;
    PositionInputs145 position_inputs_145_data;
    PositionInputs146 position_inputs_146_data;
    PositionInputs147 position_inputs_147_data;
    PositionInputs148 position_inputs_148_data;
    PositionInputs149 position_inputs_149_data;
    PositionInputs150 position_inputs_150_data;
    PositionInputs151 position_inputs_151_data;
    PositionInputs152 position_inputs_152_data;
    PositionInputs153 position_inputs_153_data;
    PositionInputs154 position_inputs_154_data;
    PositionInputs155 position_inputs_155_data;
    PositionInputs156 position_inputs_156_data;
    PositionInputs157 position_inputs_157_data;
    PositionInputs158 position_inputs_158_data;
    PositionInputs159 position_inputs_159_data;
    PositionInputs160 position_inputs_160_data;
    PositionInputs161 position_inputs_161_data;
    PositionInputs162 position_inputs_162_data;
    PositionInputs163 position_inputs_163_data;
    PositionInputs164 position_inputs_164_data;
    PositionInputs165 position_inputs_165_data;
    PositionInputs166 position_inputs_166_data;
    PositionInputs167 position_inputs_167_data;
    PositionInputs168 position_inputs_168_data;
    PositionInputs169 position_inputs_169_data;
    PositionInputs170 position_inputs_170_data;
    PositionInputs171 position_inputs_171_data;
    PositionInputs172 position_inputs_172_data;
    PositionInputs173 position_inputs_173_data;
    PositionInputs174 position_inputs_174_data;
    PositionInputs175 position_inputs_175_data;
    PositionInputs176 position_inputs_176_data;
    PositionInputs177 position_inputs_177_data;
    PositionInputs178 position_inputs_178_data;
    PositionInputs179 position_inputs_179_data;
    PositionInputs180 position_inputs_180_data;
    PositionInputs181 position_inputs_181_data;
    PositionInputs182 position_inputs_182_data;
    PositionInputs183 position_inputs_183_data;
    PositionInputs184 position_inputs_184_data;
    PositionInputs185 position_inputs_185_data;
    PositionInputs186 position_inputs_186_data;
    PositionInputs187 position_inputs_187_data;
    PositionInputs188 position_inputs_188_data;
    PositionInputs189 position_inputs_189_data;
    PositionInputs190 position_inputs_190_data;
    PositionInputs191 position_inputs_191_data;
    PositionInputs192 position_inputs_192_data;
    PositionInputs193 position_inputs_193_data;
    PositionInputs194 position_inputs_194_data;
    PositionInputs195 position_inputs_195_data;
    PositionInputs196 position_inputs_196_data;
    PositionInputs197 position_inputs_197_data;
    PositionInputs198 position_inputs_198_data;
    PositionInputs199 position_inputs_199_data;
    PositionConnSynapse0 position_conn_synapse0_data;
    PositionConnSynapse1 position_conn_synapse1_data;
    PositionConnSynapse2 position_conn_synapse2_data;
    PositionConnSynapse3 position_conn_synapse3_data;
    PositionConnSynapse4 position_conn_synapse4_data;
    PositionConnSynapse5 position_conn_synapse5_data;
    PositionConnSynapse6 position_conn_synapse6_data;
    PositionConnSynapse7 position_conn_synapse7_data;
    PositionConnSynapse8 position_conn_synapse8_data;
    PositionConnSynapse9 position_conn_synapse9_data;
    PositionConnSynapse10 position_conn_synapse10_data;
    PositionConnSynapse11 position_conn_synapse11_data;
    PositionConnSynapse12 position_conn_synapse12_data;
    PositionConnSynapse13 position_conn_synapse13_data;
    PositionConnSynapse14 position_conn_synapse14_data;
    PositionConnSynapse15 position_conn_synapse15_data;
    PositionConnSynapse16 position_conn_synapse16_data;
    PositionConnSynapse17 position_conn_synapse17_data;
    PositionConnSynapse18 position_conn_synapse18_data;
    PositionConnSynapse19 position_conn_synapse19_data;
    PositionConnSynapse20 position_conn_synapse20_data;
    PositionConnSynapse21 position_conn_synapse21_data;
    PositionConnSynapse22 position_conn_synapse22_data;
    PositionConnSynapse23 position_conn_synapse23_data;
    PositionConnSynapse24 position_conn_synapse24_data;
    PositionConnSynapse25 position_conn_synapse25_data;
    PositionConnSynapse26 position_conn_synapse26_data;
    PositionConnSynapse27 position_conn_synapse27_data;
    PositionConnSynapse28 position_conn_synapse28_data;
    PositionConnSynapse29 position_conn_synapse29_data;
    PositionConnSynapse30 position_conn_synapse30_data;
    PositionConnSynapse31 position_conn_synapse31_data;
    PositionConnSynapse32 position_conn_synapse32_data;
    PositionConnSynapse33 position_conn_synapse33_data;
    PositionConnSynapse34 position_conn_synapse34_data;
    PositionConnSynapse35 position_conn_synapse35_data;
    PositionConnSynapse36 position_conn_synapse36_data;
    PositionConnSynapse37 position_conn_synapse37_data;
    PositionConnSynapse38 position_conn_synapse38_data;
    PositionConnSynapse39 position_conn_synapse39_data;
    PositionConnSynapse40 position_conn_synapse40_data;
    PositionConnSynapse41 position_conn_synapse41_data;
    PositionConnSynapse42 position_conn_synapse42_data;
    PositionConnSynapse43 position_conn_synapse43_data;
    PositionConnSynapse44 position_conn_synapse44_data;
    PositionConnSynapse45 position_conn_synapse45_data;
    PositionConnSynapse46 position_conn_synapse46_data;
    PositionConnSynapse47 position_conn_synapse47_data;
    PositionConnSynapse48 position_conn_synapse48_data;
    PositionConnSynapse49 position_conn_synapse49_data;
    PositionConnSynapse50 position_conn_synapse50_data;
    PositionConnSynapse51 position_conn_synapse51_data;
    PositionConnSynapse52 position_conn_synapse52_data;
    PositionConnSynapse53 position_conn_synapse53_data;
    PositionConnSynapse54 position_conn_synapse54_data;
    PositionConnSynapse55 position_conn_synapse55_data;
    PositionConnSynapse56 position_conn_synapse56_data;
    PositionConnSynapse57 position_conn_synapse57_data;
    PositionConnSynapse58 position_conn_synapse58_data;
    PositionConnSynapse59 position_conn_synapse59_data;
    PositionConnSynapse60 position_conn_synapse60_data;
    PositionConnSynapse61 position_conn_synapse61_data;
    PositionConnSynapse62 position_conn_synapse62_data;
    PositionConnSynapse63 position_conn_synapse63_data;
    PositionConnSynapse64 position_conn_synapse64_data;
    PositionConnSynapse65 position_conn_synapse65_data;
    PositionConnSynapse66 position_conn_synapse66_data;
    PositionConnSynapse67 position_conn_synapse67_data;
    PositionConnSynapse68 position_conn_synapse68_data;
    PositionConnSynapse69 position_conn_synapse69_data;
    PositionConnSynapse70 position_conn_synapse70_data;
    PositionConnSynapse71 position_conn_synapse71_data;
    PositionConnSynapse72 position_conn_synapse72_data;
    PositionConnSynapse73 position_conn_synapse73_data;
    PositionConnSynapse74 position_conn_synapse74_data;
    PositionConnSynapse75 position_conn_synapse75_data;
    PositionConnSynapse76 position_conn_synapse76_data;
    PositionConnSynapse77 position_conn_synapse77_data;
    PositionConnSynapse78 position_conn_synapse78_data;
    PositionConnSynapse79 position_conn_synapse79_data;
    PositionConnSynapse80 position_conn_synapse80_data;
    PositionConnSynapse81 position_conn_synapse81_data;
    PositionConnSynapse82 position_conn_synapse82_data;
    PositionConnSynapse83 position_conn_synapse83_data;
    PositionConnSynapse84 position_conn_synapse84_data;
    PositionConnSynapse85 position_conn_synapse85_data;
    PositionConnSynapse86 position_conn_synapse86_data;
    PositionConnSynapse87 position_conn_synapse87_data;
    PositionConnSynapse88 position_conn_synapse88_data;
    PositionConnSynapse89 position_conn_synapse89_data;
    PositionConnSynapse90 position_conn_synapse90_data;
    PositionConnSynapse91 position_conn_synapse91_data;
    PositionConnSynapse92 position_conn_synapse92_data;
    PositionConnSynapse93 position_conn_synapse93_data;
    PositionConnSynapse94 position_conn_synapse94_data;
    PositionConnSynapse95 position_conn_synapse95_data;
    PositionConnSynapse96 position_conn_synapse96_data;
    PositionConnSynapse97 position_conn_synapse97_data;
    PositionConnSynapse98 position_conn_synapse98_data;
    PositionConnSynapse99 position_conn_synapse99_data;
    PositionConnSynapse100 position_conn_synapse100_data;
    PositionConnSynapse101 position_conn_synapse101_data;
    PositionConnSynapse102 position_conn_synapse102_data;
    PositionConnSynapse103 position_conn_synapse103_data;
    PositionConnSynapse104 position_conn_synapse104_data;
    PositionConnSynapse105 position_conn_synapse105_data;
    PositionConnSynapse106 position_conn_synapse106_data;
    PositionConnSynapse107 position_conn_synapse107_data;
    PositionConnSynapse108 position_conn_synapse108_data;
    PositionConnSynapse109 position_conn_synapse109_data;
    PositionConnSynapse110 position_conn_synapse110_data;
    PositionConnSynapse111 position_conn_synapse111_data;
    PositionConnSynapse112 position_conn_synapse112_data;
    PositionConnSynapse113 position_conn_synapse113_data;
    PositionConnSynapse114 position_conn_synapse114_data;
    PositionConnSynapse115 position_conn_synapse115_data;
    PositionConnSynapse116 position_conn_synapse116_data;
    PositionConnSynapse117 position_conn_synapse117_data;
    PositionConnSynapse118 position_conn_synapse118_data;
    PositionConnSynapse119 position_conn_synapse119_data;
    PositionConnSynapse120 position_conn_synapse120_data;
    PositionConnSynapse121 position_conn_synapse121_data;
    PositionConnSynapse122 position_conn_synapse122_data;
    PositionConnSynapse123 position_conn_synapse123_data;
    PositionConnSynapse124 position_conn_synapse124_data;
    PositionConnSynapse125 position_conn_synapse125_data;
    PositionConnSynapse126 position_conn_synapse126_data;
    PositionConnSynapse127 position_conn_synapse127_data;
    PositionConnSynapse128 position_conn_synapse128_data;
    PositionConnSynapse129 position_conn_synapse129_data;
    PositionConnSynapse130 position_conn_synapse130_data;
    PositionConnSynapse131 position_conn_synapse131_data;
    PositionConnSynapse132 position_conn_synapse132_data;
    PositionConnSynapse133 position_conn_synapse133_data;
    PositionConnSynapse134 position_conn_synapse134_data;
    PositionConnSynapse135 position_conn_synapse135_data;
    PositionConnSynapse136 position_conn_synapse136_data;
    PositionConnSynapse137 position_conn_synapse137_data;
    PositionConnSynapse138 position_conn_synapse138_data;
    PositionConnSynapse139 position_conn_synapse139_data;
    PositionConnSynapse140 position_conn_synapse140_data;
    PositionConnSynapse141 position_conn_synapse141_data;
    PositionConnSynapse142 position_conn_synapse142_data;
    PositionConnSynapse143 position_conn_synapse143_data;
    PositionConnSynapse144 position_conn_synapse144_data;
    PositionConnSynapse145 position_conn_synapse145_data;
    PositionConnSynapse146 position_conn_synapse146_data;
    PositionConnSynapse147 position_conn_synapse147_data;
    PositionConnSynapse148 position_conn_synapse148_data;
    PositionConnSynapse149 position_conn_synapse149_data;
    PositionConnSynapse150 position_conn_synapse150_data;
    PositionConnSynapse151 position_conn_synapse151_data;
    PositionConnSynapse152 position_conn_synapse152_data;
    PositionConnSynapse153 position_conn_synapse153_data;
    PositionConnSynapse154 position_conn_synapse154_data;
    PositionConnSynapse155 position_conn_synapse155_data;
    PositionConnSynapse156 position_conn_synapse156_data;
    PositionConnSynapse157 position_conn_synapse157_data;
    PositionConnSynapse158 position_conn_synapse158_data;
    PositionConnSynapse159 position_conn_synapse159_data;
    PositionConnSynapse160 position_conn_synapse160_data;
    PositionConnSynapse161 position_conn_synapse161_data;
    PositionConnSynapse162 position_conn_synapse162_data;
    PositionConnSynapse163 position_conn_synapse163_data;
    PositionConnSynapse164 position_conn_synapse164_data;
    PositionConnSynapse165 position_conn_synapse165_data;
    PositionConnSynapse166 position_conn_synapse166_data;
    PositionConnSynapse167 position_conn_synapse167_data;
    PositionConnSynapse168 position_conn_synapse168_data;
    PositionConnSynapse169 position_conn_synapse169_data;
    PositionConnSynapse170 position_conn_synapse170_data;
    PositionConnSynapse171 position_conn_synapse171_data;
    PositionConnSynapse172 position_conn_synapse172_data;
    PositionConnSynapse173 position_conn_synapse173_data;
    PositionConnSynapse174 position_conn_synapse174_data;
    PositionConnSynapse175 position_conn_synapse175_data;
    PositionConnSynapse176 position_conn_synapse176_data;
    PositionConnSynapse177 position_conn_synapse177_data;
    PositionConnSynapse178 position_conn_synapse178_data;
    PositionConnSynapse179 position_conn_synapse179_data;
    PositionConnSynapse180 position_conn_synapse180_data;
    PositionConnSynapse181 position_conn_synapse181_data;
    PositionConnSynapse182 position_conn_synapse182_data;
    PositionConnSynapse183 position_conn_synapse183_data;
    PositionConnSynapse184 position_conn_synapse184_data;
    PositionConnSynapse185 position_conn_synapse185_data;
    PositionConnSynapse186 position_conn_synapse186_data;
    PositionConnSynapse187 position_conn_synapse187_data;
    PositionConnSynapse188 position_conn_synapse188_data;
    PositionConnSynapse189 position_conn_synapse189_data;
    PositionConnSynapse190 position_conn_synapse190_data;
    PositionConnSynapse191 position_conn_synapse191_data;
    PositionConnSynapse192 position_conn_synapse192_data;
    PositionConnSynapse193 position_conn_synapse193_data;
    PositionConnSynapse194 position_conn_synapse194_data;
    PositionConnSynapse195 position_conn_synapse195_data;
    PositionConnSynapse196 position_conn_synapse196_data;
    PositionConnSynapse197 position_conn_synapse197_data;
    PositionConnSynapse198 position_conn_synapse198_data;
    PositionConnSynapse199 position_conn_synapse199_data;
} RollingCylinderStrings;

// rolling_cylinder_strings Initialisation function
void RollingCylinderStringsInit(RollingCylinderStrings* me);

// rolling_cylinder_strings Execution function
void RollingCylinderStringsRun(RollingCylinderStrings* me);

#endif // ROLLING_CYLINDER_STRINGS_H_