#ifndef CONFIG_H
#define CONFIG_H

#define NOSCILLATORS 4
#define NSTATES 8
#define USEGRAPHICS 1
#define LOGDATA 0
#define USEHOPFCTLR 0
#define USELENGTHCTLR 0
#define USELENGTHZMQCTLR 1
#define USEPHASEOSCCTLR 0

#define USEMARCYAML 1

#endif